### ISSUE TITLE
MobCannon Gadget

### ISSUE THREAD

**Issue by pookeythekid** [SlaydeVentures/MVPGadgets#22]
I would do this myself, but I'm trying to hold off on Java development for now; the MobCannon updates kinda killed me. :P

Anyway, the title says it. It'd be fairly nice to make MobCannon into a gadget. It can get a little inconvenient if you want to have fun spamming mobs, and you have to resubmit a command every time you want to do so.

**Comment by SlaydeVentures** [comment]
Yeah, it would be nice to make this into a gadget. Maybe @TGRHavoc can do it. ;)

**Comment by SlaydeVentures** [comment]
Issue closed. Gadget added.
